version: '3.8'
services:
  db:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: prueba

  admin:
    image: adminer
    ports:
      - 8080:8080
